/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.games_services.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CatalogPlacedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1295145413872399453L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CatalogPlacedEvent\",\"namespace\":\"com.example.games_services.event\",\"fields\":[{\"name\":\"gameNumber\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CatalogPlacedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CatalogPlacedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CatalogPlacedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CatalogPlacedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CatalogPlacedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CatalogPlacedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CatalogPlacedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CatalogPlacedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CatalogPlacedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence gameNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CatalogPlacedEvent() {}

  /**
   * All-args constructor.
   * @param gameNumber The new value for gameNumber
   */
  public CatalogPlacedEvent(java.lang.CharSequence gameNumber) {
    this.gameNumber = gameNumber;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return gameNumber;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: gameNumber = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'gameNumber' field.
   * @return The value of the 'gameNumber' field.
   */
  public java.lang.CharSequence getGameNumber() {
    return gameNumber;
  }


  /**
   * Sets the value of the 'gameNumber' field.
   * @param value the value to set.
   */
  public void setGameNumber(java.lang.CharSequence value) {
    this.gameNumber = value;
  }

  /**
   * Creates a new CatalogPlacedEvent RecordBuilder.
   * @return A new CatalogPlacedEvent RecordBuilder
   */
  public static com.example.games_services.event.CatalogPlacedEvent.Builder newBuilder() {
    return new com.example.games_services.event.CatalogPlacedEvent.Builder();
  }

  /**
   * Creates a new CatalogPlacedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CatalogPlacedEvent RecordBuilder
   */
  public static com.example.games_services.event.CatalogPlacedEvent.Builder newBuilder(com.example.games_services.event.CatalogPlacedEvent.Builder other) {
    if (other == null) {
      return new com.example.games_services.event.CatalogPlacedEvent.Builder();
    } else {
      return new com.example.games_services.event.CatalogPlacedEvent.Builder(other);
    }
  }

  /**
   * Creates a new CatalogPlacedEvent RecordBuilder by copying an existing CatalogPlacedEvent instance.
   * @param other The existing instance to copy.
   * @return A new CatalogPlacedEvent RecordBuilder
   */
  public static com.example.games_services.event.CatalogPlacedEvent.Builder newBuilder(com.example.games_services.event.CatalogPlacedEvent other) {
    if (other == null) {
      return new com.example.games_services.event.CatalogPlacedEvent.Builder();
    } else {
      return new com.example.games_services.event.CatalogPlacedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for CatalogPlacedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CatalogPlacedEvent>
    implements org.apache.avro.data.RecordBuilder<CatalogPlacedEvent> {

    private java.lang.CharSequence gameNumber;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.games_services.event.CatalogPlacedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.gameNumber)) {
        this.gameNumber = data().deepCopy(fields()[0].schema(), other.gameNumber);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing CatalogPlacedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.games_services.event.CatalogPlacedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.gameNumber)) {
        this.gameNumber = data().deepCopy(fields()[0].schema(), other.gameNumber);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'gameNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getGameNumber() {
      return gameNumber;
    }


    /**
      * Sets the value of the 'gameNumber' field.
      * @param value The value of 'gameNumber'.
      * @return This builder.
      */
    public com.example.games_services.event.CatalogPlacedEvent.Builder setGameNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.gameNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'gameNumber' field has been set.
      * @return True if the 'gameNumber' field has been set, false otherwise.
      */
    public boolean hasGameNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'gameNumber' field.
      * @return This builder.
      */
    public com.example.games_services.event.CatalogPlacedEvent.Builder clearGameNumber() {
      gameNumber = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CatalogPlacedEvent build() {
      try {
        CatalogPlacedEvent record = new CatalogPlacedEvent();
        record.gameNumber = fieldSetFlags()[0] ? this.gameNumber : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CatalogPlacedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<CatalogPlacedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CatalogPlacedEvent>
    READER$ = (org.apache.avro.io.DatumReader<CatalogPlacedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.gameNumber);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.gameNumber = in.readString(this.gameNumber instanceof Utf8 ? (Utf8)this.gameNumber : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.gameNumber = in.readString(this.gameNumber instanceof Utf8 ? (Utf8)this.gameNumber : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










