services:

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - eshop-network
  games-service:
    image: games-service
    build:
      context: ./games_service
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Edem78s3
      MYSQL_PORT: 3306
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - eshop-network
  shoppingcart-service:
    image: shoppingcart-service
    build:
      context: ./shoppingCart_service
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Edem78s3
      MYSQL_PORT: 3306
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - eshop-network

  api-gateway-service:
    image: api-gateway-service
    build:
      context: ./demo
      dockerfile: Dockerfile
    environment:
      CATALOG_URL: http://games-service:8081
      SHOPPINGCART_URL: http://shoppingcart-service:8082
    ports:
      - "9000:9000"
    networks:
      - eshop-network
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    ports:
      - "3308:3306"
    volumes:
      - ./docker/mysql_keycloak/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Edem78s3
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    networks:
      - eshop-network
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "/opt/keycloak-21.0.0/bin/kc.sh", "start-dev", "--import-realm" ]
    environment:
      JAVA_OPTS: -Dnet.bytebuddy.experimental=true
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak-mysql:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql
    networks:
      - eshop-network
networks:
  eshop-network:
    driver: bridge
