INSERT INTO t_category(name_category)
values ('Action'),
       ('Adventure'),
       ('RPG'),
       ('Shooter'),
       ('Horror'),
       ('Puzzle'),
       ('Simulation'),
       ('Strategy'),
       ('Open World'),
       ('Multiplayer'),
       ('Platformer'),
       ('Sports'),
       ('Racing'),
       ('Battle Royale'),
       ('Sandbox'),
       ('Survival'),
       ('Stealth'),
       ('Visual Novel'),
       ('MMORPG'),
       ('AR'),
       ('VR'),
       ('Card Games'),
       ('Educational'),
       ('Rhythm'),
       ('Idle Games'),
       ('Tactical Shooter'),
       ('Platform Fighter'),
       ('Crafting'),
       ('Narrative Adventure'),
       ('Fighting'),
       ('Escape Room'),
       ('Gacha'),
       ('Action-Adventure'),
       ('MMO'),
       ('Roguelike'),
       ('Roguelite'),
       ('Stealth Action'),
       ('Survival Horror'),
       ('Interactive Fiction'),
       ('Management Simulation'),
       ('Cooking Games'),
       ('Pet Simulation'),
       ('Trivia'),
       ('Word Games'),
       ('Clicker Games'),
       ('Narrative-Driven'),
       ('Beat ''em Up'),
       ('Pinball'),
       ('Deck-Building'),
       ('Board Games'),
       ('Family Games'),
       ('Fitness Games'),
       ('Music Games'),
       ('Historical'),
       ('Farming Simulation'),
       ('Gambling Games'),
       ('City Building'),
       ('Tactical RPG'),
       ('E-sports'),
       ('Life Simulation'),
       ('Collectible Card Games'),
       ('Crossover');